### ISSUE TITLE
cargo build fails

### ISSUE THREAD

**Issue by pkmorrison** [theryangeary/choose#22] opened 2020-06-14 13:28 UTC
$ cargo build --release
error: failed to parse lock file at: /home/pete/stuff/choose/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`

**Comment by theryangeary** [comment] 2020-06-14 21:14
Hi @pkmorrison thanks for reporting this. Can you tell me what commit you are working with? (`git log -n 1`). In the meantime, you should be able to delete Cargo.lock, rebuild, and it should select appropriate PackageId's for you.

**Comment by pkmorrison** [comment] 2020-06-15 13:48
Hi Ryan,
Thanks for the tip of removing Cargo.lock. I am a rust newbie.
The compile worked.

Here is the output of:
$ git log -n 1
commit 152b4fb77d5497e8a8601727cfef082133a60bff (HEAD -> master, tag:
v1.2.0, origin/master, origin/develop, origin/HEAD)
Author: Ryan Geary <rtgnj42@gmail.com>
Date:   Mon Jun 8 23:23:33 2020 -0400

    Bump version to 1.2.0

**Comment by theryangeary** [comment] 2020-06-15 22:06
Alright I think it may have been an issue with your environment. Closing as I cannot reproduce.

**Closed by theryangeary** 2020-06-15 22:06 UTC

**Comment by pkmorrison** [comment] 2020-06-16 20:00
Thanks Ryan
